### ISSUE TITLE
Update Saxon-HE dependency to 9.7

### ISSUE THREAD

**Issue by ezhukov** [IDPF/epubcheck#674]
There are two deps in pom.xml on Saxon. One is on 9.4 another is on 9.5.
I tried changing these to 9.7 and encountered 7 compilation errors.
I would really appreciate if you could rebase to latest Saxon version in your next release.

Thanks for your work on epubcheck!
Eugene

**Comment by tofi86** [comment]
See #647 for another Saxon discussion.

**Comment by mkraetke** [comment]
Hi, I recently build epubcheck with Saxon 9.6.0-7 to use epubcheck as XProc extension step along with XML Calabash (which comes with the same Saxon version). You can find my changes to the epubcheck sources in this commit: 21cd661a19b58084175c97cb0e46ffd38ff23c58

If you want to update to Saxon 9.6.0-7, I can make a PR.

best, Martin

**Comment by tofi86** [comment]
> There are two deps in pom.xml on Saxon. One is on 9.4 another is on 9.5.

The 9.4 dependency is a maven build plugin dependency and does not need to be changed!

The 9.5 dependency is the "real" code dependency. We are in the middle of upgrading this to Saxon 9.6 in issue #647 and PullRequest #767

**Comment by tofi86** [comment]
FYI: We will update to Saxon 9.6.0-10 soon with PR #767.

**Comment by tofi86** [comment]
Saxon 9.7 would also be a nice-to-have for @oxygenxml:

*@raducoravu wrote in https://github.com/IDPF/epubcheck/issues/647#issuecomment-330132745:*

> Oxygen XML Editor 19.1 will come bundled with Saxon 9.7.0.19 and EPUB Checked 4.0.2 (just as 19.0 did). Until now we have been patching a couple of EPUB Checker classes which did not work with 9.7 (having copies of the same classes which were rewritten to be compatible with 9.7 in our own JAR library).
> So we have our workarounds for this.... but probably when an EPUB Checker version is released to support Saxon 9.7 we can remove our patches.

We should probably consider updating from 9.5 to 9.7 instead from 9.5 to 9.6 (PR #767). Assigning this to milestone 4.1.

**Comment by tofi86** [comment]
Any thoughts on upgrading to latest Saxon 9.7?
That would be 9.7.0.20 from July 31 2017

@rdeltour ?

**Comment by raducoravu** [comment]
Oxygen XML Editor 20 will probably update its internal Saxon libraries to Saxon 9.8. So we'll still be out of phase with the EPUB Checker, but it does not matter much, we can probably make it work in one way or another.

**Comment by ezhukov** [comment]
On Thu, Nov 30, 2017 at 1:12 AM, Tobias Fischer
<notifications@github.com> wrote:
> Any thoughts on upgrading to latest Saxon 9.7?
> That would be 9.7.0.20 from July 31 2017

Hello,

According to [1], there is no 9.7.0.20, but 9.7.0.10 is the last one
in 9.7 series, which is also packaged in Debian.
Version 9.8 lacks some essential configuration files (for comparison
[2] and [3]), that's why I haven't considered packaging it for Debian
yet. Probably need to contact the upstream about that.

Eugene

[1] https://dev.saxonica.com/repos/archive/opensource/tags/
[2] https://dev.saxonica.com/repos/archive/opensource/tags/9.7.0.10/hej/
[3] https://dev.saxonica.com/repos/archive/opensource/tags/9.8.0.2/hej/

**Comment by rdeltour** [comment]
> Any thoughts on upgrading to latest Saxon 9.7?

If we're going to upgrade Saxon, I would even go for the latest version (9.8 at the time of writing).

@tofi86 Do you think we can do that for 4.1? I've not looked at the details, but there probably a few API changes and we have to make sure that the extension functions provided by EpubCheck (notably to report error line numbers) are working OK.

**Comment by ezhukov** [comment]
I use this patch [1] in Debian to build and run EpubCheck 4.0.2 with
Saxon-HE 9.7.0.10.
[1] https://anonscm.debian.org/cgit/pkg-java/epubcheck.git/tree/debian/patches/compatibility_with_saxon_9.7.patch

**Comment by mkraetke** [comment]
Looks like most of the changes of your patch are already implemented with this PR https://github.com/IDPF/epubcheck/pull/767. I can have a look into the Saxon API changes from 9.6 to 9.8 and create another PR if you all agree?

**Comment by tofi86** [comment]
@ezhukov I found 9.7.0.20 on maven: https://mvnrepository.com/artifact/net.sf.saxon/Saxon-HE/9.7.0-20

@rdeltour sure, I would also be okay with upgrading to 9.8 as long as we can still support Java 7 with it, right? don't know system reqs for 9.8
If @mkraetke could take a look at the API things that would be great.

**Comment by ezhukov** [comment]
On Thu, Nov 30, 2017 at 7:19 PM, Tobias Fischer
<notifications@github.com> wrote:
> @ezhukov I found 9.7.0.20 on maven:
> https://mvnrepository.com/artifact/net.sf.saxon/Saxon-HE/9.7.0-20
Unfortunately I cannot find source code for that release. In Debian we
build everything from source and do not rely on maven repositories. I
would appreciate if you would stick with the official 9.7.0.10/9.8.0.2
release.

At this point I'd like to emphasize the importance of reproducible-builds.org.

**Comment by rdeltour** [comment]
@tofi86 
> I would also be okay with upgrading to 9.8 as long as we can still support Java 7 with it, right? don't know system reqs for 9.8

Yeah, I don’t know either.

> If @mkraetke could take a look at the API things that would be great.

👍

@ezhukov 
> Unfortunately I cannot find source code for that release.

The source code for Saxon-HE is [available on SourceForge](https://sourceforge.net/projects/saxon/files/Saxon-HE/).

**Comment by mkraetke** [comment]
The good news is that just a few code changes were necessary to compile epubcheck with Saxon 9.8. The bad news is that I get plenty of error messages because Saxon 9.8 HE no longer supports XSLT 1.0 and Jing's schematron implementation relies on XSLT 1.0.

@rdeltour Concluding from the pom.xml, this version of Jing comes from Daisy? Perhaps one of your colleagues may have a look into the issue. Here is my fork of epubcheck:
 https://github.com/mkraetke/epubcheck/commit/7a7ec3b07f159dd93136bdd1d74157a110099103

**Comment by rdeltour** [comment]
> @rdeltour Concluding from the pom.xml, this version of Jing comes from Daisy?

It's a mavenized* version of Jing, but otherwise comes straight from Jing's source code, with no change as far as I can remember ([see the POM used to compile it](https://github.com/daisy/osgi-libs/blob/master/jing/pom.xml))

(*) and OSGified, although it doesn't matter for EpubCheck.

**Comment by tofi86** [comment]
Thanks for testing this Martin!

So conclusion is we have to stick to Saxon 9.6 (currently implemented) or Saxon 9.7 (worth a try if it still supports XSLT 1.0).

**Comment by mkraetke** [comment]
It should be safe to update to Saxon 9.7.0.21 without any code changes, except the one in the pom.xml. All tests passed with this version.

**Comment by tofi86** [comment]
👉 PR #822

**Comment by raducoravu** [comment]
Actually according to the Saxon docs starting from Saxon 9.8.0.7, XSLT 1.0 backwards-compatibility mode is reinstated in Saxon-HE.

**Comment by mkraetke** [comment]
I've made a PR in order to update to Saxon 9.8: https://github.com/IDPF/epubcheck/pull/830

**Comment by tofi86** [comment]
Saxon dependency updated to 9.8.0-8 with PR #830 by @mkraetke. Thanks!
